{{/*
SPDX-License-Identifier: AGPL-3.0-only
SPDX-FileCopyrightText: 2023 - 2025 Univention GmbH
*/}}

---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: "{{ include "common.names.fullname" . }}"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
data:

  PROVISIONING_API_BASE_URL: {{ .Values.provisioningApi.connection.baseUrl | quote }}
  PROVISIONING_API_USERNAME: {{ .Values.provisioningApi.auth.username | quote }}
  MAX_ACKNOWLEDGEMENT_RETRIES: {{ required "The parameter \".Values.provisioningApi.config.maxAcknowledgementRetries\" is required." .Values.provisioningApi.config.maxAcknowledgementRetries | quote }}

  DOMAINNAME: "{{ .Values.oxConnector.domainName }}"
  OX_MASTER_ADMIN: "{{ .Values.oxConnector.oxMasterAdmin }}"
  OX_MASTER_PASSWORD: "{{ .Values.oxConnector.oxMasterPassword }}"
  LOCAL_TIMEZONE: "{{ .Values.oxConnector.oxLocalTimezone }}"
  OX_LANGUAGE: "{{ .Values.oxConnector.oxLanguage }}"
  DEFAULT_CONTEXT: "{{ .Values.oxConnector.oxDefaultContext }}"
  OX_SMTP_SERVER: "{{ .Values.oxConnector.oxSmtpServer }}"
  OX_IMAP_SERVER: "{{ .Values.oxConnector.oxImapServer }}"
  OX_SOAP_SERVER: "{{ .Values.oxConnector.oxSoapServer }}"
  LOG_LEVEL: "{{ .Values.oxConnector.logLevel }}"
  wait-for-api.sh: |
    #!/bin/bash
    until curl -s ${PROVISIONING_API_BASE_URL} > /dev/null; do
      echo "Waiting for API"
      sleep 2
    done

    echo "Success, the Provisioning API is available"
