# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---

apiVersion: "v1"
kind: "Secret"
type: "Opaque"
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  ldap_secret: {{ .Values.oxConnector.ldapPassword | b64enc | quote }}
  ca_cert: {{ .Values.oxConnector.caCert | b64enc | quote }}

...
