{{/*
SPDX-License-Identifier: AGPL-3.0-only
SPDX-FileCopyrightText: 2026 Univention GmbH
*/}}

{{- if not (.Values.openXchange.database.existingSecret).name }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ include "common.names.fullname" . }}-db-connection-string"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
type: "Opaque"
stringData:
  OX_CONNECTOR_DB: {{ required "Either \".Values.openXchange.oxDbConnectionString\" or \".Values.openXchange.database.existingSecret.name\" is required." .Values.openXchange.oxDbConnectionString | quote }}
{{- end }}
