# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

{{- if not (.Values.openXchange.auth.existingSecret).name }}
{{- $name := include "nubus-common.secrets.name" (dict "defaultNameSuffix" "ox-master-password" "context" .) | quote -}}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ $name }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
stringData:
  password: {{ .Values.openXchange.auth.password | required "Either Values.openXchange.auth.existingSecret or Values.openXchange.auth.password is required" | quote }}
{{- end }}
