# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---

include:
  - project: "univention/documentation/sphinx-docker"
    file: "pipeline/sphinx.yml"

docs-linkcheck:
  stage: "build"
  extends: ".sphinx-linkcheck-template"
  rules:
    - changes:
      - "$DOCS_DIR/**/*"

docs-spelling:
  stage: "build"
  extends: ".sphinx-spelling-template"
  rules:
    - changes:
      - "$DOCS_DIR/**/*"

docs-html:
  stage: "build"
  extends: ".sphinx-html-template"
  rules:
    - changes:
      - "$DOCS_DIR/**/*"

docs-pdf:
  stage: "build"
  extends: ".sphinx-pdf-template"
  rules:
    - changes:
      - "$DOCS_DIR/**/*"

docs-merge-to-one-artifact:
  stage: "merge"
  extends: ".sphinx-merge-template"
  needs:
    - job: "docs-html"
    - job: "docs-pdf"
    - job: "docs-spelling"
      artifacts: false
    - job: "docs-linkcheck"
      artifacts: false
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
      changes:
        - "$DOCS_DIR/**/*"
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - "$DOCS_DIR/**/*"
      when: "manual"

docs-review:
  extends: ".sphinx-review-template"
  stage: "merge"
  needs:
    - job: "docs-merge-to-one-artifact"
  rules:
    - changes:
      - "$DOCS_DIR/**/*"

# The template has inherit:variables:false to prevent the passing of pipeline
# variables to downstream, and therefore $DOCS_DIR is not available here.
docs-create-production-merge-request:
  stage: "production"
  extends: ".sphinx-docs-merge-request-template"
  needs:
    - job: "docs-merge-to-one-artifact"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - "docs/**/*"

...
