# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks:
      - id: "check-added-large-files"
        name: "check for added large files"
      - id: "check-executables-have-shebangs"
        name: "check that executables have shebangs"
      - id: "check-merge-conflict"
        name: "check for merge conflicts"
      - id: "check-yaml"
        name: "check yaml"
        exclude: "^helm/.+/templates/"
      - id: "end-of-file-fixer"
        name: "fix end of files"
        exclude: "^helm/.+/README.md$"
      - id: "fix-encoding-pragma"
        name: "fix python encoding pragma"
        args:
          - "--remove"
      - id: "trailing-whitespace"
        name: "trim trailing whitespace"

  - repo: "https://github.com/compilerla/conventional-pre-commit"
    rev: "v3.0.0"
    hooks:
      - id: "conventional-pre-commit"
        stages: ["commit-msg"]

  - repo: "https://github.com/pre-commit/mirrors-autopep8"
    rev: "v2.0.4"
    hooks:
      - id: "autopep8"
        name: "autopep8"
        args:
          - "--recursive"
          - "--in-place"
          # "E203 - Remove extraneous whitespace."
          #  conflicts with black
          - "--ignore=E203"

  - repo: "https://github.com/psf/black"
    rev: "23.12.1"
    hooks:
      - id: "black"
        args:
          - "--skip-string-normalization"
          - "--line-length=79"
          - "--target-version=py311"

  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.1.9"
    hooks:
      - id: "ruff"
        name: "ruff"
        args:
          - "check"
          - "--fix"
          - "--show-source"
          - "--exit-non-zero-on-fix"
          - "--extend-select=COM"
          # E501 Line too long (<chars> > 88 characters)
          - "--ignore=E501"

  - repo: "https://github.com/pycqa/flake8"
    rev: "6.1.0"
    hooks:
      - id: "flake8"
        name: "flake8"

  - repo: "https://github.com/pylint-dev/pylint"
    rev: "v3.0.3"
    hooks:
      - id: "pylint"
        name: "pylint"

  - repo: "https://gitlab.com/univention/pre-commit-hooks/pre-commit-shell"
    rev: "v1.0.6+uv1"
    hooks:
      - id: "shell-lint"
        name: "Shell Syntax Check"
        args:
          - "--enable=all"

  - repo: "https://github.com/hadolint/hadolint"
    rev: "v2.12.1-beta"
    hooks:
      - id: "hadolint"
        name: "Lint Dockerfiles"
        types: ["dockerfile"]
        exclude: "^Dockerfile.standalone.dockerignore$"

  - repo: "https://gitlab.com/univention/pre-commit-hooks/docker-compose-check"
    rev: "7702a8801a158b8595569dd29e2dd655d8a08310"
    hooks:
      - id: "docker-compose-check"
        name: "Validate docker-compose files"

  - repo: "https://github.com/gruntwork-io/pre-commit"
    rev: "v0.1.23"
    hooks:
      - id: "helmlint"
        name: "helmlint"

  - repo: "https://github.com/norwoodj/helm-docs"
    rev: "v1.12.0"
    hooks:
      - id: "helm-docs"
        name: "Helm Docs"
        args:
          - "--chart-search-root=helm"
          - "--template-files=README.md.gotmpl"
        always_run: true
      - id: "helm-docs-built"
        name: "Helm Docs Built"

  - repo: "https://git.knut.univention.de/univention/dist/pre-commit-hooks/addlicense"
    rev: "v1.0.1"
    hooks:
      - id: "addlicense"
        name: "Check or add license headers to files"

...
