ARG PROD_APP_IMG

FROM ${PROD_APP_IMG}

RUN apk add --no-cache vim

COPY univention-ox-provisioning/requirements_tests.txt tests/ /oxp/tests/
RUN pip3 install --no-cache-dir --compile --upgrade -r /oxp/tests/requirements_tests.txt && \
	python3 -m pytest --collect-only /oxp/tests && \
	rm -f /oxp/tests/requirements_tests.txt
