
# This Dockerfile defines the standalone listener-service for OX
# it is based upon the ox-connector image for the appcenter.

# Always build this image with `DOCKER_BUILDKIT=1`
# Without it the wrong .dockerignore file will be used

ARG UCS_BASE_IMAGE_TAG=5.2.6-build.20260706@sha256:e82e71bbc6008e440a72078b459a2cef2f3a7333a4680a8bfb6448469490e2d6
ARG UCS_BASE_IMAGE=gitregistry.knut.univention.de/univention/dev/projects/ucs-base-image/ucs-base
###############################################################################
# Reference ox-connector as source for listener_trigger dependencies
# based on alpine:3.14
# hadolint ignore=DL3007
ARG APPCENTER_BASE_IMAGE_TAG=0.32.0
FROM gitregistry.knut.univention.de/univention/dev/projects/open-xchange/connector/ox-connector-appcenter:${APPCENTER_BASE_IMAGE_TAG} AS ox-connector

###############################################################################
# Reference UCS image as source for python dependencies

FROM ${UCS_BASE_IMAGE}:${UCS_BASE_IMAGE_TAG} AS debian-python-deps

RUN \
  DEBIAN_FRONTEND=noninteractive \
  apt-get --assume-yes --verbose-versions --no-install-recommends install \
  # libgdbm.so.6 for python dbm.gnu
  libgdbm6=1.23-3* \
  # libicui18n.so.72 for python lxml.etree
  libicu72=72.* \
  # libxml2.so.2 for python lxml.etree
  libxml2=2.9.* \
  # libxslt.so.1 for python lxml.etree and ${PYPKG}/zeep/utils.py
  libxslt1.1=1.1.* \
  # for python3-zeep
  python3-cached-property=1.5.* \
  # defusedxml.lxml.fromstring for python3-zeep
  python3-defusedxml=0.7.* \
  # for dbm.gnu used by app/listener_trigger
  python3-gdbm=3.11.* \
  # for python isodate used by zeep
  python3-isodate=0.6.* \
  # dependency lxml.etree of ${PYPKG}/zeep/utils.py
  python3-lxml=4.9.* \
  # pyasn1.error.PyAsn1Error for ${PYPKG}/ldap/controls/__init__.py
  python3-pyasn1-modules \
  python3-pyasn1=0.4.* \
  # dependency pytz of ${PYPKG}/zeep/xsd/types/builtins.py
  python3-tz=2022.7.* \
  # dependency zeep.exceptions of ${PYPKG}/univention/ox/provisioning/helpers.py
  python3-zeep=4.2.* \
  python3-tenacity
  # python3-minimal \
  # python3.9-minimal

###############################################################################
# Final debian container near to distroless
FROM ${UCS_BASE_IMAGE}:${UCS_BASE_IMAGE_TAG} AS final

SHELL ["/bin/sh", "-eux", "-c"]

# debian:bookworm
ARG PYPKG=/usr/local/lib/python3.11/dist-packages

# debian-python-deps
ARG PDPKG=/usr/lib/python3/dist-packages

ARG version

LABEL \
  "description"="UCS Open-Xchange provisioning service" \
  "version"="$version"

RUN \
  DEBIAN_FRONTEND=noninteractive \
  apt-get -V install --assume-yes --verbose-versions --no-install-recommends \
    # for dbm.gnu used by app/listener_trigger
    # python3-gdbm
    ca-certificates=2023* \
    jq=1.* \
    libpython3.11-minimal=3.11.* \
    libpython3.11-stdlib=3.11.* \
    libpython3.11=3.11.* \
    # for univention/ox/provisioning/helpers.py
    python3-ldap \
    procps=2:4.0.* \
    python3-minimal=3.11.* \
    python3-pip=23.0.* \
    python3.11-minimal=3.11.* && \
  # Avoid unused dependency on PIL
  echo "" > "${PYPKG}/PIL.py" && \
  pip3 install --break-system-packages --no-cache-dir \
    nubus-provisioning-common=='v0.64.0' nubus-provisioning-consumer=='v0.64.0' --index-url https://git.knut.univention.de/api/v4/projects/882/packages/pypi/simple \
    appdirs==1.4.* \
    platformdirs==2.6.* \
    udm-rest-api-client[sync]==0.0.2

# install appcenter listener script to use as package
COPY app/listener_trigger ${PYPKG}/listener_trigger.py

# glue-code to let the consumer directly execute the listener_trigger
COPY ./standalone-files /

# dependency univention.ox.provisioning.helpers of ${PYPKG}/listener_trigger.py
COPY --from=ox-connector /usr/lib/python3.9/site-packages/univention/ox/provisioning/ ${PYPKG}/univention/ox/provisioning/

# dependency zeep.exceptions of ${PYPKG}/univention/ox/provisioning/helpers.py
COPY --from=debian-python-deps ${PDPKG}/zeep/ ${PYPKG}/zeep/

COPY --from=debian-python-deps ${PDPKG}/tenacity/ ${PYPKG}/tenacity/

# dependency zeep of ${PYPKG}/zeep/settings.py
COPY --from=ox-connector /usr/lib/python3.9/site-packages/attr/ ${PYPKG}/attr/

COPY --from=ox-connector \
  # dependency six of /usr/sbin/ucr
  /usr/lib/python3.9/site-packages/six.py \

  ${PYPKG}/

# dependency requests_file of ${PYPKG}/zeep/transports.py
COPY --from=ox-connector /usr/lib/python3.9/site-packages/requests_file/ ${PYPKG}/requests_file/

COPY --from=debian-python-deps \
  # dependency dbm.gnu of /usr/local/lib/python3.11/dist-packages/listener_trigger.py
  /usr/lib/x86_64-linux-gnu/libgdbm.so.6.0.0 \
  # dependency lxml.etree of ${PYPKG}zeep/utils.py
  /usr/lib/x86_64-linux-gnu/libxslt.so.1.1.35 \
  /usr/lib/x86_64-linux-gnu/libexslt.so.0.8.20 \
  /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.14 \
  /usr/lib/x86_64-linux-gnu/libicui18n.so.72.1 \
  /usr/lib/x86_64-linux-gnu/libicuuc.so.72.1 \
  /usr/lib/x86_64-linux-gnu/libicudata.so.72.1 \
  /usr/lib/x86_64-linux-gnu/

RUN \
  ln --symbolic --force libgdbm.so.6.0.0 /usr/lib/x86_64-linux-gnu/libgdbm.so.6 && \
  ln --symbolic --force libxslt.so.1.1.35 /usr/lib/x86_64-linux-gnu/libxslt.so.1 && \
  ln --symbolic --force libexslt.so.0.8.20 /usr/lib/x86_64-linux-gnu/libexslt.so.0 && \
  ln --symbolic --force libxml2.so.2.9.14 /usr/lib/x86_64-linux-gnu/libxml2.so.2 && \
  ln --symbolic --force libicui18n.so.72.1 /usr/lib/x86_64-linux-gnu/libicui18n.so.72 && \
  ln --symbolic --force libicuuc.so.72.1 /usr/lib/x86_64-linux-gnu/libicuuc.so.72 && \
  ln --symbolic --force libicudata.so.72.1 /usr/lib/x86_64-linux-gnu/libicudata.so.72

COPY --from=ox-connector \
  # dependency univention.ox.soap.backend_base of ${PYPKG}/univention/ox/provisioning/contexts.py
  /usr/lib/python3.9/site-packages/univention/ox/soap/backend_base.py \

  # dependency univention.ox.soap.backend of ${PYPKG}/univention/ox/soap/backend_base.py
  /usr/lib/python3.9/site-packages/univention/ox/soap/backend.py \

  # dependency univention.ox.soap.config of ${PYPKG}/univention/ox/soap/backend.py
  /usr/lib/python3.9/site-packages/univention/ox/soap/config.py \

  # dependency univention.ox.soap.credentials of ${PYPKG}/univention/ox/soap/backend.py
  /usr/lib/python3.9/site-packages/univention/ox/soap/credentials.py \

  # dependency univention.ox.soap.types of ${PYPKG}/univention/ox/soap/credentials.py
  /usr/lib/python3.9/site-packages/univention/ox/soap/types.py \

  # dependency univention.ox.soap.services of ${PYPKG}/univention/ox/soap/types.py
  /usr/lib/python3.9/site-packages/univention/ox/soap/services.py \

  ${PYPKG}/univention/ox/soap/

# dependency requests of ${PYPKG}/zeep/transports.py
COPY --from=ox-connector /usr/lib/python3.9/site-packages/requests ${PYPKG}/requests

# dependency urllib3 of ${PYPKG}/requests/__init__.py
COPY --from=ox-connector /usr/lib/python3.9/site-packages/urllib3 ${PYPKG}/urllib3

# dependency certifi of ${PYPKG}/requests/certs.py
COPY --from=ox-connector /usr/lib/python3.9/site-packages/certifi ${PYPKG}/certifi

# dependency lxml.etree of ${PYPKG}/zeep/utils.py
COPY --from=debian-python-deps ${PDPKG}/lxml/ ${PYPKG}/lxml/

# dependency dbm.gnu of /usr/local/lib/python3.11/dist-packages/listener_trigger.py
COPY --from=debian-python-deps /usr/lib/python3.11/lib-dynload/_gdbm.cpython-311-x86_64-linux-gnu.so /usr/lib/python3.11/lib-dynload/

# dependency chardet of /usr/local/lib/python3.11/dist-packages/requests/compat.py
COPY --from=ox-connector /usr/lib/python3.9/site-packages/chardet ${PYPKG}/chardet/

# dependency idna of /usr/local/lib/python3.11/dist-packages/requests/packages.py
COPY --from=ox-connector /usr/lib/python3.9/site-packages/idna/ ${PYPKG}/idna/

COPY --from=debian-python-deps \
  # dependency cached_property.threaded_cached_property of ${PYPKG}/zeep/xsd/elements/indicators.py
  ${PDPKG}/cached_property.py \

  ${PYPKG}/

# dependency isodate of ${PYPKG}/zeep/xsd/types/builtins.py
COPY --from=debian-python-deps ${PDPKG}/isodate/ ${PYPKG}/isodate/

# dependency pytz of ${PYPKG}/zeep/xsd/types/builtins.py
COPY --from=debian-python-deps ${PDPKG}/pytz/ ${PYPKG}/pytz/

# dependency defusedxml.lxml.fromstring of ${PYPKG}/zeep/loader.py
COPY --from=debian-python-deps ${PDPKG}/defusedxml/ ${PYPKG}/defusedxml/

# dependency requests_toolbelt of ${PYPKG}/zeep/wsdl/bindings/soap.py
COPY --from=debian-python-deps ${PDPKG}/requests_toolbelt/ ${PYPKG}/requests_toolbelt/

# dependency pyasn1.error.PyAsn1Error of ${PYPKG}/ldap/controls/__init__.py
COPY --from=debian-python-deps ${PDPKG}/pyasn1/ ${PYPKG}/pyasn1/
COPY --from=debian-python-deps ${PDPKG}/pyasn1_modules/ ${PYPKG}/pyasn1_modules/

ENV PYTHON_DIST_PACKAGES="/usr/local/lib/python3.11/dist-packages"

COPY entrypoint.sh /entrypoint.d/75-entrypoint.sh
COPY share/migrate_fupo_to_shared_account.py /usr/local/share/ox-connector/resources/migrate_fupo_to_shared_account.py

RUN \
  python3 -V && \
  python3 -m site && \
  python3 -c 'from univention.ox.provisioning import helpers, run'

CMD ["/usr/bin/python3", "/consumer.py"]

###############################################################################
# A separate stage for tests
FROM final AS test

COPY --from=ghcr.io/astral-sh/uv:0.9.3@sha256:ecfea7316b266ba82a5e9efb052339ca410dd774dc01e134a30890e6b85c7cd1 /uv /usr/local/bin/uv

# NOTE: Needed for the ldap dependency which is being compiled.
# hadolint ignore=DL3008
RUN DEBIAN_FRONTEND=noninteractive \
  apt-get -V install --assume-yes --verbose-versions --no-install-recommends \
    gcc \
    libldap2-dev \
    libsasl2-dev \
    libssl-dev \
    make \
    python3-dev

# Set PYTHONPATH to allow importing from migrate.py for tests
ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PYTHON_DOWNLOADS=never \
    UV_PYTHON=python3.11 \
    PATH=/test-env/.venv/bin:$PATH \
    PYTHONPATH="/:$PYTHONPATH"

COPY ./share/change_attribute_mapping.py /usr/local/share/ox-connector/resources/change_attribute_mapping.py
COPY ./univention-ox-provisioning /test-env/univention-ox-provisioning
COPY ./univention-ox-soap-api /test-env/univention-ox-soap-api
COPY ./tests /test-env/tests
COPY ./uv.lock /test-env/uv.lock
COPY ./pyproject.toml /test-env/pyproject.toml

WORKDIR /test-env

RUN --mount=type=cache,target=/root/.cache \
    uv sync \
    --locked \
    --no-install-project && \
    uv export -o ./requirements.txt

RUN uv sync --locked --no-editable

WORKDIR /
