# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 Univention GmbH

---

version: "3.9"

services:
  ox-connector-standalone:
    container_name: "ox-connector-standalone"
    platform: "linux/amd64"
    build:
      context: "."
      target: "k8s"
      args:
        - "version=4.0.0"
    environment:
      # -- Provisioning API
      # The base URL the provisioning API is reachable at. (e.g. "https://provisioning-api")
      PROVISIONING_API_BASE_URL: ""
      # The username to authenticate with
      PROVISIONING_API_USERNAME: "ox-connector"
      # The password to authenticate with
      PROVISIONING_API_PASSWORD: ""

      # -- OX CONNECTOR
      # OX-Mail-Domain to generate OX-email-addresses
      DOMAINNAME: example.org
      # OX Admin username (the OX Admin can create, modify, delete contexts; has to exist)
      OX_MASTER_ADMIN: "oxadminmaster"
      # OX Admin password
      OX_MASTER_PASSWORD: "ox-password"
      # Default timezone for new users
      LOCAL_TIMEZONE: "Europe/Berlin"
      # Default language for new users
      OX_LANGUAGE: "de_DE"
      # Default context for users (has to exist)
      DEFAULT_CONTEXT: "10"
      # Default SMTP server for new users (if not set explicitely there)
      OX_SMTP_SERVER: "smtp://example.org:587"
      # Default IMAP server for new users (if not set explicitely there)
      OX_IMAP_SERVER: "imap://example.org:143"
      # The server where Open-Xchange is installed
      OX_SOAP_SERVER: "https://ox.example.org"
      # Log level: DEBUG, INFO, WARNING, ERROR
      LOG_LEVEL: "DEBUG"

  k8s-tests:
    container_name: "ox-connector-k8s-tests"
    image: gitregistry.knut.univention.de/univention/dev/projects/open-xchange/connector/ox-connector-standalone-test:latest
    volumes:
      - "./tests/:/test-env/tests:ro"
      - "${KUBE_CONFIG:-~/.kube/config}:/root/.kube/config:ro"
    environment:
      # This specific value is tested in tests/test_user.py::test_modify_mailserver
      OX_IMAP_SERVER: imap://127.0.0.1:143
    working_dir: /test-env
    entrypoint: ["python3", "-m", "pytest", "-vll", "--k8s"]
    command: ["tests"]

  dev:
    container_name: "ox-connector-dev"
    image: gitregistry.knut.univention.de/univention/dev/projects/open-xchange/connector/ox-connector-standalone-test:latest
    volumes:
        # needs to be mounted rw, because legacy setuptools is used which writes egg files
      - "./univention-ox-provisioning/:/test-env/univention-ox-provisioning:rw"
      - "./univention-ox-soap-api/:/test-env/univention-ox-soap-api:rw"
      - "./tests:/test-env/tests:ro"
      - "./uv.lock:/test-env/uv.lock:rw"
      - "./pyproject.toml:/test-env/pyproject.toml:ro"
      - "./standalone-files:/test-env/standalone-files:ro"
      - "./scripts:/test-env/scripts:ro"
      - "${KUBE_CONFIG:-~/.kube/config}:/root/.kube/config:ro"
      - "uv-cache:/root/.cache/uv"
      - "shared-test-data:/tmp/"
      - "shared-test-data2:/var/lib/univention-appcenter/apps/ox-connector/data/"
    working_dir: /test-env
    entrypoint: ["scripts/remote_consumer.py"]

volumes:
  uv-cache:
  shared-test-data:
  shared-test-data2:
