# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

[project]
name = "ox-connector-metapackage"
description = "Metapackage to support local development and testruns"
version = "0.1.0"
package-mode = false
authors = [
    {name = "Univention GmbH", email = "packages@univention.de"},
]
license = {text = "AGPL-3.0-only"}
requires-python = ">=3.9"

dependencies = [
  "univention-ox-provisioning",
  "univention-ox-soap-api",
]

[dependency-groups]
dev = [
  "pytest",
  "uritemplate",
  "kubernetes",
  "pytest-mock>=3.15.1",
  "pdbpp>=0.11.7",
  "python-dateutil>=2.9.0.post0",
]

[tool.uv]
# NOTE: The managed Python does not have gdbm available (at least on MacOS).
# Test via:
#    python -c "import dbm.gnu"
python-preference = "system"

[tool.uv.sources]
univention-ox-provisioning = { path = "./univention-ox-provisioning/", editable = true }
univention-ox-soap-api = { path = "./univention-ox-soap-api/", editable = true }

[tool.pytest.ini_options]
markers = [
    "k8s_skip(reason): mark test as expected to skip in Kubernetes context, provide a reason"
]
