# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025-2026 Univention GmbH

[project]
name = "ox-connector"
description = "OX Connector - provision Nubus entities to Open-Xchange"
version = "4.0.0"
package-mode = false
authors = [
    {name = "Univention GmbH", email = "packages@univention.de"},
]
license = {text = "AGPL-3.0-only"}
requires-python = "==3.13.*"

dependencies = [
  "univention-ox-provisioning",
  "univention-ox-soap-api",
  "nubus-provisioning-consumer==2.2.4",
  "nubus-provisioning-common==2.2.4",
  "udm-rest-api-client[sync]==0.1.2",
  "lancelog==0.3.4",
]

[dependency-groups]
dev = [
  "pytest==9.1.1",
  "pytest-cov==7.1.0",
  "pytest-mock==3.15.1",
  "uritemplate==4.2.0",
  "kubernetes==36.0.3",
  "pdbpp==0.12.1",
  "python-dateutil==2.9.0.post0",
  "tenacity==9.1.4",
]
dev-scripts = [
  "paramiko==5.0.0",
  "udm-rest-api-client[cli]==0.1.2",
  "kubernetes==36.0.3",
  "pyyaml==6.0.3",
  "psycopg2==2.9.13",
  "portforward==0.7.6",
]

[tool.uv]
python-preference = "system"

[tool.uv.workspace]
members = ["univention-ox-provisioning", "univention-ox-soap-api"]

[tool.uv.sources]
univention-ox-provisioning = { workspace = true }
univention-ox-soap-api = { workspace = true }
nubus-provisioning-consumer = { index = "nubus" }
nubus-provisioning-common = { index = "nubus" }
lancelog = { index = "gitlab" }

[[tool.uv.index]]
name = "nubus"
url = "https://git.knut.univention.de/api/v4/projects/882/packages/pypi/simple"  # provisioning
explicit = true

[[tool.uv.index]]
name = "gitlab"
url = "https://git.knut.univention.de/api/v4/projects/1449/packages/pypi/simple"  # lancelog
explicit = true
default = false

[tool.pytest.ini_options]
markers = [
    "k8s_skip(reason): mark test as expected to skip in Kubernetes context, provide a reason"
]
