# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025-2026 Univention GmbH

[project]
name = "ox-connector"
description = "OX Connector - provision Nubus entities to Open-Xchange"
version = "4.0.0"
package-mode = false
authors = [
    {name = "Univention GmbH", email = "packages@univention.de"},
]
license = {text = "AGPL-3.0-only"}
requires-python = "==3.11.*"

dependencies = [
  "univention-ox-provisioning",
  "univention-ox-soap-api",
  "nubus-provisioning-consumer",
  "nubus-provisioning-common",
]

[dependency-groups]
dev = [
  "pytest",
  "pytest-cov>=4.1.0",
  "pytest-mock>=3.15.1",
  "uritemplate",
  "kubernetes",
  "pdbpp>=0.11.7",
  "python-dateutil>=2.9.0.post0",
  "tenacity",
  "udm-rest-api-client[sync]"
]

[tool.uv]
python-preference = "system"

[tool.uv.sources]
univention-ox-provisioning = { path = "./univention-ox-provisioning", editable = true  }
univention-ox-soap-api = { path = "./univention-ox-soap-api", editable = true  }
nubus-provisioning-consumer = { index = "nubus" }
nubus-provisioning-common = { index = "nubus" }

[[tool.uv.index]]
name = "nubus"
url = "https://git.knut.univention.de/api/v4/projects/882/packages/pypi/simple"
explicit = true

[tool.pytest.ini_options]
markers = [
    "k8s_skip(reason): mark test as expected to skip in Kubernetes context, provide a reason"
]
