sonar.projectKey=univention_dev_projects_open-xchange_connector_00560e30-413a-400f-9c12-4bd856a0eada
sonar.qualitygate.wait=true
sonar.python.version=3.11
sonar.links.homepage=https://git.knut.univention.de/univention/dev/projects/open-xchange/connector
sonar.links.scm=https://git.knut.univention.de/univention/dev/projects/open-xchange/connector
