sonar.projectKey=univention_dev_projects_open-xchange_connector_d562203b-ad0c-4e56-9862-59a1d4685fd1
sonar.qualitygate.wait=true
sonar.python.version=3.11
sonar.links.homepage=https://git.knut.univention.de/univention/dev/projects/open-xchange/connector
sonar.links.scm=https://git.knut.univention.de/univention/dev/projects/open-xchange/connector
