# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH

---
include:
  - project: "univention/dev/nubus-for-k8s/common-ci"
    ref: "v1.42.1"
    file:
      - "defaults/nubus-workflow.yaml"
  - local: ".gitlab-ci/deploy-ox-lab.yaml"
    inputs:
      namespace: "${DEPLOY_NAMESPACE}"
      domain: "${DEPLOY_SUBDOMAIN}-ox.review.univention.dev"
      needs:
        - pipeline-configuration
        - deploy-namespace

stages:
  - prepare
  - deploy
  - test
  - cleanup


variables:
  DEPLOY_NAMESPACE: "ci-ox-con-${CI_COMMIT_REF_SLUG}"
  DEPLOY_SUBDOMAIN: "ci-ox-con-${CI_COMMIT_REF_SLUG}"
  ENVIRONMENT_NAME: "${CI_COMMIT_REF_SLUG}/e2e-testrun-${DEPLOY_NAMESPACE}"
  NUBUS_HELM_BRANCH: "develop"
  NUBUS_CHART_VERSION: "*"
  OX_CONNECTOR_READY_TIMEOUT: "5m"
  HELMFILE_IMAGE: "ghcr.io/helmfile/helmfile:v1.5.2@sha256:0d51e5a30aaf87e03451cbe462e9be3a614dc5aba9eae4e1f158858315755d3d"

pipeline-configuration:
  stage: prepare
  script:
    - echo "Original values which may be modified:"
    - |
      cat <<EOF
      DEPLOY_NAMESPACE: ${DEPLOY_NAMESPACE}
      DEPLOY_SUBDOMAIN: ${DEPLOY_SUBDOMAIN}
      NUBUS_HELM_BRANCH: ${NUBUS_HELM_BRANCH}
      EOF
    # "-ox" is appended to the subdomain for the ox deployment, so shorten it to 63 -3
    # namespace is used as hostname for some nubus charts so also shorten it
    - |
      cat > deploy.env <<EOF
      DEPLOY_NAMESPACE=$( echo ${DEPLOY_NAMESPACE:0:60} | sed 's/-$//' )
      DEPLOY_SUBDOMAIN=$( echo ${DEPLOY_SUBDOMAIN:0:60} | sed 's/-$//' )
      RELEASE_VERSION=${RELEASE_VERSION}
      SEMANTIC_VERSION=${SEMANTIC_VERSION}
      EOF
    - echo "dotenv content:"
    - cat deploy.env
  variables:
    GIT_STRATEGY: none
  artifacts:
    reports:
      dotenv: deploy.env


deploy-namespace:
  stage: "prepare"
  needs:
    - pipeline-configuration
  image: "$HELMFILE_IMAGE"
  script:
    - echo "Cluster information:"
    - kubectl cluster-info

    - echo "Ensure cleanup of namespace"
    - >
      kubectl delete namespace "${DEPLOY_NAMESPACE}"
      --wait
      --timeout=600s
      --ignore-not-found

    - echo "Creating namespace ${DEPLOY_NAMESPACE}"
    - |
      kubectl create -f - <<EOT
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${DEPLOY_NAMESPACE}
          annotations:
            kubernetes.io/description: Used and managed by the CI system of the OX Connector via Gitlab
            nubus.univention.dev/owner: Nautilus Team
            nubus.univention.dev/repository: ${CI_PROJECT_URL}
            nubus.univention.dev/pipeline: ${CI_PIPELINE_URL}
      EOT
  variables:
    GIT_STRATEGY: none


deploy-nubus:
  needs:
    - deploy-namespace
    - pipeline-configuration
  stage: deploy
  image: "$HELMFILE_IMAGE"
  script:
    - export CHART_VERSION=${NUBUS_CHART_VERSION}
    - export OX_CHART_VERSION=${RELEASE_VERSION}
    - export REVIEW_PREFIX=${DEPLOY_SUBDOMAIN}

    - echo "Grab the nubus-helm sources to use the nubus ci helmfile"
    - "[ ! -e nubus-helm ]"
    - >
      git clone
      --depth 1
      --branch "${NUBUS_HELM_BRANCH}"
      https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/univention/dev/nubus-for-k8s/nubus-helm.git

    - echo "Deploy nubus via nubus-helm/ci/helmfile"
    - pushd nubus-helm/ci
    # Workaround for ingress-nginx webhook rejecting older charts'
    # `pathType: Exact` + `path: /$` ingresses.
    - helm plugin install ../.gitlab-ci/helm-plugins/fix-ingress-pathtype
    - helmfile -n "${DEPLOY_NAMESPACE}" --state-values-file=../../ci/nubus-ci-overrides.yaml.gotmpl --post-renderer=fix-ingress-pathtype sync
    - popd

    - >
      echo TESTS_UDM_ADMIN_PASSWORD=$(
      kubectl get secret nubus-ldap-server-admin -n ${DEPLOY_NAMESPACE}
      -o jsonpath='{.data.password}' | base64 -d
      ) >> deploy.env
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: ${ENVIRONMENT_NAME}
    url: https://${DEPLOY_SUBDOMAIN}.portal.review.univention.dev
    on_stop: stop-deployment
    deployment_tier: development
  resource_group: gaia-${DEPLOY_NAMESPACE}

deploy-ox-connector:
  needs:
    - deploy-namespace
    - pipeline-configuration
    - ox-lab-deploy
  stage: deploy
  image: "$HELMFILE_IMAGE"
  script:
    - export OX_CHART_VERSION=${RELEASE_VERSION}
    - export REVIEW_PREFIX=${DEPLOY_SUBDOMAIN}

    - echo "Grab the nubus-helm sources to get the gaia ci config"
    - "[ ! -e nubus-helm ]"
    - >
      git clone
      --depth 1
      --branch "${NUBUS_HELM_BRANCH}"
      https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/univention/dev/nubus-for-k8s/nubus-helm.git

    - echo "Deploy ox-connector via ci/helmfile"
    - pushd ci
    - helmfile -n "${DEPLOY_NAMESPACE}" sync
    - popd
  environment:
    name: ${ENVIRONMENT_NAME}
    url: https://${DEPLOY_SUBDOMAIN}.portal.review.univention.dev
    on_stop: stop-deployment
    deployment_tier: development
  resource_group: gaia-${DEPLOY_NAMESPACE}


wait-until-ready:
  needs:
    - pipeline-configuration
    - deploy-nubus
    - ox-lab-deploy
    - deploy-ox-connector
  stage: deploy
  image: "$HELMFILE_IMAGE"
  script:
    - echo "Waiting for the ox-connector Pod to become ready"
    - >
      kubectl -n "${DEPLOY_NAMESPACE}" rollout status --timeout="${OX_CONNECTOR_READY_TIMEOUT}"
      statefulset -l "app.kubernetes.io/name=ox-connector"


collect-k8s-skip-tests:
  needs:
    - pipeline-configuration
    - wait-until-ready
    # NOTE: Ensure that the artifacts are available, e.g. the admin password.
    - deploy-nubus
  stage: "deploy"
  image: "${CI_REGISTRY_IMAGE}/ox-connector-standalone-test:${RELEASE_VERSION}"
  script:
    - >
      pytest --k8s --k8s-namespace="${DEPLOY_NAMESPACE}"
      --collect-only
      -m "k8s_skip"
      tests
  variables:
    DOMAINNAME: review.univention.dev
    OX_ENABLE_DEPUTY_PERMISSIONS: "true"
    OX_SOAP_SERVER: https://${DEPLOY_SUBDOMAIN}-ox.review.univention.dev
    OX_MASTER_ADMIN: stub-value
    OX_MASTER_PASSWORD: stub-value
    OX_SMTP_SERVER: stub-value
    OX_IMAP_SERVER: imap://dovecot-ce:143
    TESTS_UDM_ADMIN_USERNAME: cn=admin
    STANDALONE_KUBERNETES_TESTS: "1"
    LDAP_BASE: dc=univention-organization,dc=intranet
    DEFAULT_CONTEXT: 10
    PORTAL_HOST: ${DEPLOY_SUBDOMAIN}.portal.review.univention.dev


run-tests-k8s:
  # Run the tests against the deployment through the Kubernetes API.
  needs:
    - pipeline-configuration
    - wait-until-ready
    # NOTE: Ensure that the artifacts are available, e.g. the admin password.
    - deploy-nubus
  stage: "deploy"
  image: "${CI_REGISTRY_IMAGE}/ox-connector-standalone-test:${RELEASE_VERSION}"
  script:
    - >
      pytest --k8s --k8s-namespace="${DEPLOY_NAMESPACE}"
      -vl --log-level=info
      -m "not k8s_skip"
      tests
  variables:
    DOMAINNAME: review.univention.dev
    OX_ENABLE_DEPUTY_PERMISSIONS: "true"
    OX_SOAP_SERVER: https://${DEPLOY_SUBDOMAIN}-ox.review.univention.dev
    OX_MASTER_ADMIN: stub-value
    OX_MASTER_PASSWORD: stub-value
    OX_SMTP_SERVER: stub-value
    OX_IMAP_SERVER: imap://dovecot-ce:143
    TESTS_UDM_ADMIN_USERNAME: cn=admin
    STANDALONE_KUBERNETES_TESTS: "1"
    LDAP_BASE: dc=univention-organization,dc=intranet
    DEFAULT_CONTEXT: 10
    PORTAL_HOST: ${DEPLOY_SUBDOMAIN}.portal.review.univention.dev
  allow_failure: true
  rules:
    - when: manual

run-tests-testimage:
  needs:
    - pipeline-configuration
    - wait-until-ready
    # NOTE: Ensure that the artifacts are available, e.g. the admin password.
    - deploy-nubus
  stage: "deploy"
  image: "$HELMFILE_IMAGE"
  script:
    - echo "Patching ox-connector StatefulSet to use test image"
    - >
      kubectl patch statefulset ox-connector \
        -n ${DEPLOY_NAMESPACE} \
        --type strategic \
        -p '
      spec:
        template:
          spec:
            containers:
            - name: main
              image: artifacts.software-univention.de/nubus-dev/images/ox-connector-standalone-test:'${RELEASE_VERSION}'
              imagePullPolicy: Always
              env:
              - name: TESTS_UDM_ADMIN_USERNAME
                value: "Administrator"
              - name: TESTS_UDM_ADMIN_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: nubus-nubus-credentials
                    key: administrator_password
              - name: DOMAINNAME
                value: "review.univention.dev"
              - name: STANDALONE_KUBERNETES_TESTS
                value: "1"
              - name: LDAP_MASTER
                value: "'${DEPLOY_NAMESPACE}'.portal.review.univention.dev"
              - name: LDAP_BASE
                value: "dc=univention-organization,dc=intranet"
      '
    - echo "Waiting for the ox-connector Pod to become ready after patch"
    - >
      kubectl -n "${DEPLOY_NAMESPACE}" rollout status --timeout=5m
      statefulset -l "app.kubernetes.io/name=ox-connector"
    - echo "Running tests inside ox-connector test image using installed environment"
    - |
      kubectl exec -n "${DEPLOY_NAMESPACE}" -i ox-connector-0 -- /bin/bash <<EOT
      pushd test-env
      pytest \
        -o cache_dir=/tmp/.pytest_cache \
        -vl \
        -m "not k8s_skip" \
        tests
      EOT
  variables:
    DOMAINNAME: review.univention.dev
    OX_ENABLE_DEPUTY_PERMISSIONS: "true"
    OX_SOAP_SERVER: https://${DEPLOY_SUBDOMAIN}-ox.review.univention.dev
    OX_MASTER_ADMIN: stub-value
    OX_MASTER_PASSWORD: stub-value
    OX_SMTP_SERVER: stub-value
    OX_IMAP_SERVER: imap://dovecot-ce:143
    TESTS_UDM_ADMIN_USERNAME: cn=admin
    STANDALONE_KUBERNETES_TESTS: "1"
    LDAP_BASE: dc=univention-organization,dc=intranet
    DEFAULT_CONTEXT: 10
    PORTAL_HOST: ${DEPLOY_SUBDOMAIN}.portal.review.univention.dev
  rules:
    - if: '$SKIP_TESTRUN == "yes"'
      when: manual
    - when: on_success


stop-deployment:
  stage: cleanup
  allow_failure: true
  needs:
    - pipeline-configuration
    - deploy-nubus
    - ox-lab-deploy
    - deploy-ox-connector
    - run-tests-testimage
  image: "$HELMFILE_IMAGE"
  script:
    - >
      kubectl delete namespace "${DEPLOY_NAMESPACE}"
      --wait
      --timeout=600s
      --ignore-not-found
  variables:
    GIT_STRATEGY: none
  environment:
    name: ${ENVIRONMENT_NAME}
    action: stop
  rules:
    - if: '$SKIP_CLEANUP == "yes"'
      when: manual
    - if: '$SKIP_TESTRUN == "yes"'
      when: manual
    - when: on_success

cleanup-failed-deployment:
  extends: stop-deployment
  rules:
    - if: '$SKIP_CLEANUP == "yes"'
      when: manual
    - when: on_failure
