#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

"""
Generate Gitlab pipeline to build Nubus documentation.

Author: Philipp Hahn 2024-03-13
Copied from the Nubus Docs repository by Nico Gulden on 2025-05-15
"""

from __future__ import annotations

import argparse
import os
from configparser import ConfigParser
from pathlib import Path

from ruamel.yaml import YAML

BASE = Path(__file__).parent  # .gilab-ci/
ROOT = BASE.parent


TARGETS = ["html", "linkcheck", "spelling", "pdf"]
DEPENDS = {
    "packaged-integration-ox": {
        "ox-connector-app",
        "ox-connector",
    },
    "ox-connector-app": {
        "ox-connector",
    },
}
SPECIAL: dict[str, dict[str, object]] = {
    "ox-connector-app": {
        "DOC_TARGET_PATH": "$DOC_TARGET_NAME/$DOC_TARGET_VERSION",
    },
    # Little version changes expected.
    # It's enough to use ``latest`` as version.
    "packaged-integration-ox": {
        "DOC_TARGET_PATH": "$DOC_TARGET_NAME/latest/$language",
    },
}


all_paths: list[str] = []
pipeline: dict[str, object] = {
    "docs-merge-to-one-artifact": {
        "extends": ".docs-merge",
        "rules": [
            {"changes": all_paths},
        ],
    },
    "review": {
        "stage": "production",
        "needs": [
            {"job": "docs-merge-to-one-artifact"},
        ],
        "script": [
            "true",
        ],
        "environment": {
            "name": "review/docs/$CI_COMMIT_REF_SLUG",
            "url": "$DOC_REVIEW_URL",
        },
        "rules": [
            {"changes": all_paths},
        ],
    },
    "docs-create-production-merge-request": {
        "extends": ".sphinx-docs-merge-request-template",
        "needs": [
            {"job": "docs-merge-to-one-artifact"},
        ],
        "rules": [
            {
                "if": '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH != "develop"',
                "changes": all_paths,
            },
        ],
    },
}


def main() -> None:
    args = parse_args()

    yaml = YAML(typ="rt")
    for head in args.yaml:
        with head.open() as fd:
            data = yaml.load(fd)
        pipeline.update(data)

    appcenter_version = read_appcenter_version()
    pipeline.setdefault("variables", {})
    pipeline["variables"]["DOC_TARGET_VERSION"] = appcenter_version

    add_jobs(pipeline)

    with args.out.open("w") as fd:
        yaml.dump(pipeline, fd)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--yaml", action="append", type=Path, default=[])
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "generated-config-doc.yml",
    )
    return parser.parse_args()


def job_name(pkg: str, target: str = "") -> str:
    return f"build {pkg}{f' {target}' if target else ''}"


def job_desc(
    pkg: str,
    path: Path,
    extends: str,
    languages: list[str],
    depends: set[str],
) -> dict[str, object]:
    variables = dict(
        SPECIAL.get(pkg, {}),
        DOCS_DIR=path.relative_to(ROOT).as_posix(),
        DOC_TARGET_NAME=path.name,
        # For special documents we need to overwrite the default DOC_TARGET_PATH
        # and pull the value from the SPECIAL dict.
        DOC_TARGET_PATH=SPECIAL.get(pkg, {}).get("DOC_TARGET_PATH", None)
        or "$DOC_TARGET_NAME/$DOC_TARGET_VERSION/$language",
    )

    if pkg == "ox-connector":
        variables["DOC_TARGET_VERSION"] = doc_target_version(
            read_appcenter_version(),
        )

    job: dict[str, object] = {
        "variables": variables,
        "extends": extends,
        "rules": [
            {
                "changes": [
                    job_path(path),
                ],
            },
        ],
        "parallel": {
            "matrix": [
                {"language": languages},
            ],
        },
    }
    if depends:
        job["needs"] = [
            {
                "job": job_name(dep, "html"),
                "optional": True,
            }
            for dep in depends
        ]

    return job


def job_path(path: Path) -> str:
    return f"{path.relative_to(ROOT).as_posix()}/**/*"


def lint_envvars(pkg: str, path: Path, extends: str) -> dict[str, object]:
    """
    This job greps in the build artifact of the HTML for references to ``:envvar:`` roles
    that don't have a linked reference.
    If this is the case, Sphinx can't resolve the corresponding ``.. envvar::`` directive.
    It means that the explanation for the envvar isn't defined or miss-spelled.
    Such cross-references need a fix and should show up in the pipeline.
    """
    variables = {
        "DOCS_DIR": path.relative_to(ROOT).as_posix(),
    }
    job: dict[str, object] = {
        "variables": variables,
        "extends": extends,
        "needs": [
            {"job": job_name(pkg, "html")},
        ],
        "rules": [
            {
                "if": "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH",
                "changes": [
                    job_path(path),
                ],
            },
        ],
    }
    return job


def find_docs() -> dict[Path, list[str]]:
    result = {}
    language = "en"
    for path in ROOT.glob("docs/*/conf.py"):
        result[path.parent] = list(
            {lang.name for lang in path.parent.glob("locales/*")} | {language},
        )
    return dict(sorted(result.items()))


def add_jobs(pipeline: dict[str, object]) -> None:
    docs = find_docs()
    for path, languages in docs.items():
        all_paths.append(job_path(path))
        all_paths.sort()
        pkg = path.name
        for target in TARGETS:
            name = job_name(pkg, target)
            job = job_desc(
                pkg,
                path,
                f".sphinx-{target}",
                languages,
                DEPENDS.get(pkg, set()),
            )
            pipeline.update({name: job})

        if pkg == "ox-connector":
            name = f"lint envvars {pkg}"
            lint_envvar = lint_envvars(
                pkg,
                path,
                ".lint-envvar-cross-reference",
            )
            pipeline.update({name: lint_envvar})


def read_appcenter_version() -> str:
    doc_target_key = os.environ.get("DOC_TARGET_VERSION")
    if doc_target_key:
        return doc_target_key

    appcenter_version = os.environ.get("APPCENTER_VERSION")
    if appcenter_version:
        return appcenter_version

    app_ini = Path(__file__).resolve().parents[1] / "app" / "ini"
    app_config = ConfigParser()
    app_config.read(app_ini)
    return app_config["Application"]["Version"]


def doc_target_version(appcenter_version: str) -> str:
    major_version = appcenter_version.split(".", 1)[0]
    return f"{major_version}.x"


if __name__ == "__main__":
    main()
