#!/usr/bin/python3

# Copyright 2020 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

"""
Entry point for listener_trigger script.
"""

import json
import logging
import os
import shutil
import sys
import time
import traceback
import requests
from requests.exceptions import Timeout, ConnectionError, HTTPError
from collections import defaultdict
from datetime import datetime
from pathlib import Path
import zeep.exceptions

from sqlalchemy import create_engine, Column, Integer, String, insert, update

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

from univention.ox.provisioning import helpers, run
from univention.ox.provisioning.db import increment_error_count, move_task_to_old, move_task_to_dead_letters, get_tasks, add_task, get_old, create_task_from_old, remove_old, remove_task

APP = "ox-connector"
DATA_DIR = Path("/var/lib/univention-appcenter/apps", APP, "data")
NEW_FILES_DIR = DATA_DIR / "listener"
OLD_FILES_DIR = NEW_FILES_DIR / "old"

log_level = os.getenv("OX_CONNECTOR_LOG_LEVEL", "INFO")
logger = logging.getLogger("univention.ox")
logger.setLevel(log_level)
handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter("%(name)s: %(message)s")
handler.setFormatter(formatter)
logger.addHandler(handler)
logger = logging.getLogger("listener")
logger.setLevel(log_level)
handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter("%(message)s")
handler.setFormatter(formatter)
logger.addHandler(handler)


if log_level == "DEBUG":
    logger = logging.getLogger("zeep.transports")
    logger.addHandler(handler)
    logger = logging.getLogger("univention.ox")


def obj_from_row(row):
    return TriggerObject(
        row.obj_id,
        row.udm_module,
        row.dn,
        json.loads(row.attrs),
        [],
        None,
    )


def _get_old_object(distinguished_name, obj_id=None):
    logger.info("Loading old object for %s", obj_id or distinguished_name)
    old = get_old(distinguished_name, obj_id)
    if old:
        return obj_from_row(old)


helpers.get_old_obj = _get_old_object


def _update_group_queue(entry_uuid):
    if entry_uuid not in GROUP_EUUID:
        create_task_from_old(entry_uuid)
        logger.info(
            "Added %s to the listener queue",
            entry_uuid,
        )
        # Register it so it is not processed twice
        GROUP_EUUID.add(entry_uuid)


helpers.update_group_queue = _update_group_queue


class TriggerObject(object):
    """
    A thin wrapper over a JSON file. Holds all the information from that
    file. May also hold information of this object from a previous run
    (needs a second, backup file for that)
    """

    def __init__(
        self,
        entry_uuid,
        object_type,
        distinguished_name,
        attributes,
        options,
        path=None,
    ):
        self.entry_uuid = entry_uuid
        self.object_type = object_type
        self.distinguished_name = distinguished_name
        self.attributes = attributes
        self.options = options
        self.old_distinguished_name = None
        self.old_attributes = None
        self.old_options = None
        self.path = path  # file where it originates from
        self._old_loaded = False
        self._enriched = {}

    def load_old(self):
        """Loads the old filename and sets attributes accordingly"""
        old = _get_old_object(None, self.entry_uuid)
        if old:
            self.old_distinguished_name = old.distinguished_name
            self.old_attributes = old.attributes
            self.old_options = []
        self._old_loaded = True

    def was_added(self):
        """
        Whether this object is new. Needs the have read an old file
        for this to give a meaningful response
        """
        if self.attributes is None:
            return False
        if not self._old_loaded:
            return None
        return self.old_distinguished_name is None

    def was_modified(self):
        """
        Whether this object was modified. Needs the have read an old
        file for this to give a meaningful response
        """
        if self.attributes is None:
            return False
        if self._old_loaded is False:
            return None
        return not self.was_added() and not self.was_deleted()

    def was_deleted(self):
        """Whether this object was deleted."""
        return self.attributes is None and self.old_attributes is not None

    def was_enriched(self):
        """Whether the obj was modified via set_attr during processing."""
        return bool(self._enriched)

    def set_attr(self, attr, value):
        """Enrich an object's attributes. Will be preserved should the
        old object be kept (i.e. files are moved at the end)"""
        if self.attributes.get(attr) != value:
            self.attributes[attr] = value
            self._enriched[attr] = value

    def __repr__(self):
        return f"Object({self.object_type!r}, {self.distinguished_name!r})"


GROUP_EUUID = set()


def main():
    """Handles listener-JSON-files"""
    # run forever and only exit on error
    for json_file in NEW_FILES_DIR.glob("*.json"):
        if os.path.basename(json_file) == "restart.json":
            continue
        logger.info("Adding a new task from %s", json_file)
        add_task(json_file)
        os.unlink(json_file)
    ret_value = 0
    stop_on_error = os.getenv("OX_CONNECTOR_STOP_ON_ERROR", "True") != "False"
    for udm_module, empty_attributes in [
            ("oxmail/oxcontext", False),
            ("oxmail/accessprofile", None),
            ("users/user", None),
            ("groups/group", None),
            ("oxmail/functional_account", None),
            ("oxresources/oxresources", None),
            ("oxmail/oxcontext", True),
    ]:
        for task in get_tasks(udm_module, empty_attributes):
            try:
                logger.info("Processing Task %s", task)
                obj = obj_from_row(task)
                obj.load_old()
                logger.info("... %r", obj)
                run(obj)
            except (HTTPError, ConnectionError, Timeout) as exc:
                logger.error("Error while handling %s", task)
                logger.exception(exc)
                increment_error_count(task.id)
                ret_value = 1
                break
            except Exception as exc:
                logger.error("Error while handling %s", task)
                logger.exception(exc)
                if stop_on_error or task.udm_module == "oxmail/oxcontext":
                    # oxcontext is so important, we can never continue here
                    increment_error_count(task.id)
                    ret_value = 1
                    break
                move_task_to_dead_letters(task.id, traceback.format_exc())
                ret_value = 1
            else:
                try:
                    GROUP_EUUID.remove(obj.entry_uuid)
                except KeyError:
                    pass
                if obj.was_deleted():
                    remove_old(obj.old_distinguished_name)
                    remove_task(task.id)
                else:
                    move_task_to_old(task.id, obj.attributes)
        else:
            # no break from stop_on_error: continue
            continue
        break
    if ret_value == 0:
        try:
            os.unlink(NEW_FILES_DIR / "restart.json")
        except OSError:
            pass
    else:
        open(NEW_FILES_DIR / "restart.json", "w")  # it is hacky, sorry
    return ret_value


if __name__ == '__main__':
    sys.exit(main())

# [EOF]
