#!/bin/bash

# Abort on nonzero exitstatus [-e]
set -o errexit
# Don't hide errors within pipes
set -o pipefail

APP_ID="ox-connector"

if [[ ! -d "/var/lib/univention-appcenter/apps/${APP_ID}/data/secrets/" ]]; then
  mkdir -pv "/var/lib/univention-appcenter/apps/${APP_ID}/data/secrets"
fi
