#!/usr/bin/python3

import os
from pathlib import Path

from univention.ox.provisioning.db import DBSession
import json

old_files = Path("/var/lib/univention-appcenter/apps/ox-connector/data/listener/old")

with DBSession() as db:
    for json_file in old_files.glob("*.json"):
        print("Migrating %s" % json_file)
        with json_file.open() as fh:
            content = json.load(fh)
        udm_module = content["udm_object_type"]
        dn = content["dn"]
        attrs = content["object"]
        obj_id = attrs.get("univentionObjectIdentifier", "")
        if not obj_id:
            print("Did not find univentionObjectIdentifier in %s. Skipping" % json_file)
            continue
        db.store_old(obj_id, udm_module, dn, attrs)
        os.remove(json_file)
