#!/bin/bash
#
# This script is meant to be a helper script for environments
# where users from old ox Appsuite installations
# weren't migrated correctly and still have empty oxContextIDNum
# attributes.
# It removes the old listener files of those users.
#
# Copyright (C) 2013-2023 Univention GmbH <http://www.univention.de/>
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.
#

APP_ID="ox-connector"

univention-ldapsearch -LLL '(&(isOXUser=OK)(!(oxContextIDNum=*)))' entryUUID | sed -ne 's,entryUUID: ,,p' | xargs -I{} rm "/var/lib/univention-appcenter/apps/$APP_ID/data/listener/old/{}.json"
