# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

services:
  test:
    image: gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:0.29.22@sha256:a9254c92372e9847e792be0793d0e731678506b073ca9828e33693b7f7dad77a
    pull_policy: always
    command: "pytest tests/"
    profiles:
      - test
    volumes:
      - "../helm/:/app/helm/"
      - "../helm-unittests/:/app/tests"
