# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

services:
  test:
    image: gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:0.29.21@sha256:2b5fde0de1b980c388a78883fc53d819f9116cf70be577351f6ebd33c9301518
    pull_policy: always
    command: "pytest tests/"
    profiles:
      - test
    volumes:
      - "../helm/:/app/helm/"
      - "../helm-unittests/:/app/tests"
