# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH


# Create system user
action: create
module: users/ldap
position: cn=users,{{ ldapBaseDn }}
properties:
  username: "oxSystemUser"
  lastname: "LDAP-system-User"
  password: {{ oxSystemUserPassword }}
  overridePWHistory: true
  overridePWLength: true
---
# Create Ox portal tile for Domain Users
action: create_or_modify
module: portals/entry
position: cn=entry,cn=portals,cn=univention,{{ ldapBaseDn }}
properties:
  name: "ox_mail"
  icon: "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI0LjEuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkViZW5lXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCAzNi4xIDI4LjMiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDM2LjEgMjguMzsiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPgoJLnN0MHtmaWxsOiMyODRENzM7fQoJLnN0MXtmaWxsOiMzQzNDM0I7fQoJLnN0MntmaWxsOiNGRkZGRkY7fQoJLnN0M3tmaWxsOiM4Nzg3ODc7fQo8L3N0eWxlPgo8cGF0aCBjbGFzcz0ic3QyIiBkPSJNMzMuNSwyNS4xVjkuN2MtMC40LDAuNS0wLjksMC45LTEuNCwxLjNjLTMuNiwyLjgtNi41LDUtOC42LDYuOGMtMC43LDAuNi0xLjIsMS0xLjcsMS4zcy0xLDAuNi0xLjcsMQoJYy0wLjcsMC4zLTEuNCwwLjUtMi4xLDAuNWgwYy0wLjYsMC0xLjMtMC4yLTIuMS0wLjVzLTEuMy0wLjctMS43LTFzLTEtMC44LTEuNy0xLjNjLTIuMS0xLjgtNS00LTguNi02LjhjLTAuNS0wLjQtMS0wLjgtMS40LTEuMwoJdjE1LjVjMCwwLjIsMC4xLDAuMywwLjIsMC41YzAuMSwwLjEsMC4zLDAuMiwwLjUsMC4yaDI5LjZjMC4yLDAsMC4zLTAuMSwwLjUtMC4yQzMzLjQsMjUuNSwzMy41LDI1LjMsMzMuNSwyNS4xeiBNMzMuNSw0VjMuNWwwLTAuMwoJTDMzLjQsM2wtMC4xLTAuMmwtMC4yLTAuMmwtMC4zLTAuMUgzLjJDMywyLjYsMi45LDIuNiwyLjgsMi44UzIuNiwzLDIuNiwzLjJjMCwyLjMsMSw0LjIsMyw1LjdjMi42LDIsNS4zLDQuMiw4LjEsNi40CgljMC4xLDAuMSwwLjMsMC4zLDAuNywwLjZjMC40LDAuMywwLjcsMC42LDAuOSwwLjhjMC4yLDAuMiwwLjUsMC40LDAuOSwwLjZjMC40LDAuMiwwLjcsMC40LDEsMC42UzE3LjgsMTgsMTgsMThoMAoJYzAuMywwLDAuNi0wLjEsMC45LTAuMnMwLjYtMC4zLDEtMC42YzAuNC0wLjIsMC43LTAuNSwwLjktMC42YzAuMi0wLjIsMC41LTAuNCwwLjktMC44czAuNi0wLjUsMC43LTAuNmMyLjgtMi4yLDUuNS00LjMsOC4xLTYuNAoJYzAuNy0wLjYsMS40LTEuNCwyLTIuM0MzMy4yLDUuNiwzMy41LDQuOCwzMy41LDR6IE0zNi4xLDMuMnYyMS45YzAsMC45LTAuMywxLjYtMC45LDIuM3MtMS40LDAuOS0yLjMsMC45SDMuMgoJYy0wLjksMC0xLjYtMC4zLTIuMy0wLjlTMCwyNiwwLDI1LjFWMy4yYzAtMC45LDAuMy0xLjYsMC45LTIuM1MyLjMsMCwzLjIsMGgyOS42YzAuOSwwLDEuNiwwLjMsMi4zLDAuOVMzNi4xLDIuMywzNi4xLDMuMnoiLz4KPC9zdmc+Cg=="
  link:
    - - en_US
      - {{ portalOxLinkBase }}/appsuite/#app=io.ox/mail
  allowedGroups:
    - 'cn=Domain Users,cn=groups,{{ ldapBaseDn }}'
  linkTarget: newwindow
  description:
    de_DE: E-Mails senden und empfangen
    en_US: Send and receive emails
  displayName:
    de_DE: Open-Xchange
    en_US: Open-Xchange
---
action: ensure_list_contains
module: portals/category
position: cn=domain-service,cn=category,cn=portals,cn=univention,{{ ldapBaseDn }}
properties:
  entries:
  - cn=ox_mail,cn=entry,cn=portals,cn=univention,{{ ldapBaseDn }}
  - cn=ox_context_admin,cn=entry,cn=portals,cn=univention,{{ ldapBaseDn }}
---
action: create
module: settings/umc_operationset
position: cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}
properties:
  name: "ox-shared-accounts"
  description: Administration for OX shared accounts
  flavor: oxmail/shared_account
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=users/user"
    - command: "udm/*"
      option: "objectType=groups/group"
    - command: "udm/*"
      option: "objectType=oxmail/shared_account_permission"
    - command: "udm/*"
      option: "objectType=oxmail/shared_account"
---
action: create
module: settings/umc_operationset
position: cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}
properties:
  name: "ox-functional-accounts"
  description: Administration for OX functional mailboxes
  flavor: oxmail/functional_account
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=users/user"
    - command: "udm/*"
      option: "objectType=oxmail/functional_account"
---
action: create
module: settings/umc_operationset
position: cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}
properties:
  name: "ox-resources"
  description: Administration for OX resources
  flavor: oxresources/oxresources
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=oxresources/*"
    - command: "udm/properties"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/query"
      option: "objectType=policies/*"
---
action: create
module: settings/umc_operationset
position: cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}
properties:
  name: "ox-context"
  description: Administration for OX contexts
  flavor: oxmail/oxcontext
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=oxmail/*"
    - command: "udm/properties"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/query"
      option: "objectType=policies/*"
...
